//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
#include "ConsecutiveReactionTestApp.h"
#include "ConsecutiveReactionApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template <>
InputParameters
validParams<ConsecutiveReactionTestApp>()
{
  InputParameters params = validParams<ConsecutiveReactionApp>();
  return params;
}

ConsecutiveReactionTestApp::ConsecutiveReactionTestApp(InputParameters parameters) : MooseApp(parameters)
{
  ConsecutiveReactionTestApp::registerAll(
      _factory, _action_factory, _syntax, getParam<bool>("allow_test_objects"));
}

ConsecutiveReactionTestApp::~ConsecutiveReactionTestApp() {}

void
ConsecutiveReactionTestApp::registerAll(Factory & f, ActionFactory & af, Syntax & s, bool use_test_objs)
{
  ConsecutiveReactionApp::registerAll(f, af, s);
  if (use_test_objs)
  {
    Registry::registerObjectsTo(f, {"ConsecutiveReactionTestApp"});
    Registry::registerActionsTo(af, {"ConsecutiveReactionTestApp"});
  }
}

void
ConsecutiveReactionTestApp::registerApps()
{
  registerApp(ConsecutiveReactionApp);
  registerApp(ConsecutiveReactionTestApp);
}

/***************************************************************************************************
 *********************** Dynamic Library Entry Points - DO NOT MODIFY ******************************
 **************************************************************************************************/
// External entry point for dynamic application loading
extern "C" void
ConsecutiveReactionTestApp__registerAll(Factory & f, ActionFactory & af, Syntax & s)
{
  ConsecutiveReactionTestApp::registerAll(f, af, s);
}
extern "C" void
ConsecutiveReactionTestApp__registerApps()
{
  ConsecutiveReactionTestApp::registerApps();
}
